### ISSUE TITLE
WGPU decides to not get a GPU anytime

### ISSUE THREAD

**Issue by td5038** [wgpu-mc/wgpu-mc#105]
CRASH REPORT BELOW:
`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-01-04 07:59:22
Description: wgpu-mc has panicked. Minecraft will now exit.
panicked at /home/td5038/wgpu-mc/rust/wgpu-mc/src/lib.rs:130:14:
called `Option::unwrap()` on a `None` value

java.lang.RuntimeException
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zjh000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)

-- This crash was caused by the Fabric mod Electrum within native Rust code. Please report this crash to the wgpu-mc developers by opening an issue and attaching this crash log at https://github.com/wgpu-mc/wgpu-mc/issues --
Details:
Stacktrace:
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zjh000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Uptime --
Details:
        JVM uptime: 11.537s
        Wall uptime: 2.018s
        High-res time: 1155.377s
        Client ticks: 23 ticks / 1.150s
Stacktrace:
        at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2564)
        at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:995)
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:140)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zjh000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
        Reload number: 1
        Reload reason: initial
        Finished: No
        Packs: vanilla, fabric

-- System Details --
Details:
        Minecraft Version: 1.20.4
        Minecraft Version ID: 1.20.4
        Operating System: Linux (amd64) version 6.6.8-cachyos
        Java Version: 17.0.7, N/A
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 226496512 bytes (216 MiB) / 926941184 bytes (884 MiB) up to 4024434688 bytes (3838 MiB)
        CPUs: 16
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 7 5800H with Radeon Graphics
        Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
        Microarchitecture: Zen 3
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 16
        Graphics card #0 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
        Graphics card #0 vendor: NVIDIA Corporation (0x10de)
        Graphics card #0 VRAM (MB): 8224.00
        Graphics card #0 deviceId: 0x2560
        Graphics card #0 versionInfo: unknown
        Graphics card #1 name: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
        Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
        Graphics card #1 VRAM (MB): 258.00
        Graphics card #1 deviceId: 0x1638
        Graphics card #1 versionInfo: unknown
        Virtual memory max (MB): 32251.39
        Virtual memory used (MB): 8140.45
        Swap memory total (MB): 24576.00
        Swap memory used (MB): 78.00
        JVM Flags: 0 total; 
        Fabric Mods: 
                fabric-api: Fabric API 0.91.3+1.20.4
                fabric-api-base: Fabric API Base 0.4.35+78d798af4f
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
                fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
                fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
                fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
                fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
                fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
                fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
                fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
                fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
                fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
                fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
                fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
                fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.19+78d798af4f
                fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
                fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
                fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
                fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
                fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
                fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
                fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
                fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
                fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
                fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
                fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
                fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
                fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
                fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
                fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
                fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
                fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
                fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
                fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
                fabricloader: Fabric Loader 0.15.3
                java: OpenJDK 64-Bit Server VM 17
                minecraft: Minecraft 1.20.4
                mixinextras: MixinExtras 0.3.2
                wgpu_mc: wgpu-mc 0.1
        Launched Version: Fabric
        Backend library: wgpu 0.18
        Backend API: wgpu-mc 0.1
        Window size: 0x0
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Universe: 400921fb54442d18
        Type: Client (map_client.txt)
        Graphics mode: fancy
        Render Distance: 12/12 chunks
        Resource Packs: fabric
        Current Language: en_us
        Locale: en_US
        CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/td5038/wgpu-mc/fabric/run/crash-reports/crash-2024-01-04_07.59.22-client.txt
`

**Comment by uku3lig** [comment]
are you on wayland or x11? and do you have renderdoc installed?

**Comment by uku3lig** [comment]
asking again, but did you have renderoc installed? if yes, that's the issue; renderdoc sadly doesn't support wayland at the time of writing.

**Comment by td5038** [comment]
I don't know what renderoc is, can you elaborate?

**Comment by td5038** [comment]
I don't have renderdoc installed

**Comment by td5038** [comment]
And the error is reproducible on X11.  I've got reciepts:
` ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-01-05 13:32:51
Description: wgpu-mc has panicked. Minecraft will now exit.
panicked at /home/td5038/wgpu-mc/rust/wgpu-mc/src/lib.rs:130:14:
called `Option::unwrap()` on a `None` value

java.lang.RuntimeException
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zzc000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)

-- This crash was caused by the Fabric mod Electrum within native Rust code. Please report this crash to the wgpu-mc developers by opening an issue and attaching this crash log at https://github.com/wgpu-mc/wgpu-mc/issues --
Details:
Stacktrace:
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:135)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zzc000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Uptime --
Details:
        JVM uptime: 9.020s
        Wall uptime: 1.631s
        High-res time: 755.871s
        Client ticks: 19 ticks / 0.950s
Stacktrace:
        at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2564)
        at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:995)
        at dev.birb.wgpu.render.Wgpu.rustPanic(Wgpu.java:140)
        at dev.birb.wgpu.rust.WgpuNative.startRendering(Native Method)
        at dev.birb.wgpu.render.Wgpu.startRendering(Wgpu.java:74)
        at net.minecraft.client.main.Main.redirect$zzc000$wgpu_mc$redirectIsRunning(Main.java:545)
        at net.minecraft.client.main.Main.main(Main.java:258)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
        Reload number: 1
        Reload reason: initial
        Finished: No
        Packs: vanilla, fabric

-- System Details --
Details:
        Minecraft Version: 1.20.4
        Minecraft Version ID: 1.20.4
        Operating System: Linux (amd64) version 6.6.8-cachyos
        Java Version: 17.0.7, N/A
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 275114768 bytes (262 MiB) / 549453824 bytes (524 MiB) up to 4024434688 bytes (3838 MiB)
        CPUs: 16
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 7 5800H with Radeon Graphics
        Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
        Microarchitecture: Zen 3
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 16
        Graphics card #0 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
        Graphics card #0 vendor: NVIDIA Corporation (0x10de)
        Graphics card #0 VRAM (MB): 8224.00
        Graphics card #0 deviceId: 0x2560
        Graphics card #0 versionInfo: unknown
        Graphics card #1 name: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
        Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
        Graphics card #1 VRAM (MB): 258.00
        Graphics card #1 deviceId: 0x1638
        Graphics card #1 versionInfo: unknown
        Virtual memory max (MB): 32251.39
        Virtual memory used (MB): 5883.04
        Swap memory total (MB): 24576.00
        Swap memory used (MB): 278.00
        JVM Flags: 0 total;
        Fabric Mods:
                fabric-api: Fabric API 0.91.3+1.20.4
                fabric-api-base: Fabric API Base 0.4.35+78d798af4f
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
                fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
                fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
                fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
                fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
                fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
                fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
                fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
                fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
                fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
                fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
                fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
                fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.19+78d798af4f
                fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
                fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
                fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
                fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
                fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
                fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
                fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
                fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
                fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
                fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
                fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
                fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
                fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
                fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
                fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
                fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
                fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
                fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
                fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
                fabricloader: Fabric Loader 0.15.3
                java: OpenJDK 64-Bit Server VM 17
                minecraft: Minecraft 1.20.4
                mixinextras: MixinExtras 0.3.2
                wgpu_mc: wgpu-mc 0.1
        Launched Version: Fabric
        Backend library: wgpu 0.18
        Backend API: wgpu-mc 0.1
        Window size: 0x0
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Universe: 400921fb54442d18
        Type: Client (map_client.txt)
        Graphics mode: fancy
        Render Distance: 12/12 chunks
        Resource Packs: fabric
        Current Language: en_us
        Locale: en_US
        CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/td5038/wgpu-mc/fabric/run/crash-reports/crash-2024-01-05_13.32.51-client.txt `

**Comment by uku3lig** [comment]
my best guess is that there is an issue with hybrid graphics, but i have no clue on how it could be solved

you could maybe try changing the power preference here: https://github.com/wgpu-mc/wgpu-mc/blob/f831b96f2e06ac09854f18ab6a344674b51423e9/rust/wgpu-mc/src/lib.rs#L125

**Comment by cohaereo** [comment]
Changing powerpreference won't solve the problem. request_adapter tries to find the first adapter that fulfills the options requested. Powerpreference is merely a priority system, not a filtering one.

The fact that request_adapter internally returns a descriptive error but `ok()`'s it to an option on the public API doesn't help with this.

**Comment by birbe** [comment]
closing as this seems more like an issue with wgpu than with wgpu-mc
