### ISSUE TITLE
Replace `static mut <NAME>: MaybeUninit<_>` with something from once_cell

### ISSUE THREAD

**Issue by i509VCB** [wgpu-mc/wgpu-mc#14]
The use of MaybeUninit in the jni linking crate is quite ugly. A once_cell::sync::Lazy should represent the case of no value much more nicely and not be nearly as prone to undefined behavior.

**Comment by Birbe** [comment]
lol i forgor 💀 
ill get on this soon, i have time to do stuff this weekend

**Comment by Birbe** [comment]
on it

**Comment by Birbe** [comment]
oh wait I already did this lol
