### ISSUE TITLE
Expanded shader pipeline support

### ISSUE THREAD

**Issue by Birbe** [wgpu-mc/wgpu-mc#29]
All pipelines should have a flexible, data-driven uniform/binding system to add support for custom features such as shadows or more advanced lighting/what-have-yous.

**Comment by JieningYu** [comment]
Considering Canvas Renderer's shader pipelines? It seems be more advanced.

**Comment by Birbe** [comment]
#38 not fully done yet but we've got a good foundation in place and it should be fully supported soon so I'll close it
