### ISSUE TITLE
Pull requests from branches on this repo trigger GitHub Actions twice

### ISSUE THREAD

**Issue by schitcrafter** [wgpu-mc/wgpu-mc#46]
How to replicate:
 - create a branch on wgpu-mc/wgpu-mc repo
 - create a pr from that branch -> master

Now, the Actions are executed twice, once for `push` once for `pull_request` (see: https://github.com/wgpu-mc/wgpu-mc/pull/45). Also they don't seem to be deterministic, as you can see in the pr - rustfmt and clippy fail for the push trigger, but not for the pull_request one.

**Comment by schitcrafter** [comment]
We could fix this by adding a `branch: master` option to the push trigger, which means that CI only runs on pushes to master or on pr's. Not sure if this is the behavior we want but it's a way

**Comment by schitcrafter** [comment]
Apparently, the pull_request action uses the code from the master branch? If you look at [the job](https://github.com/wgpu-mc/wgpu-mc/actions/runs/3507999116/jobs/5876103458), you can see it complains about `class` not being used, but when looking at the [file](https://github.com/wgpu-mc/wgpu-mc/blob/13e979d7ecd493daf6f93f7475d335f8d00322d7/rust/wgpu-mc-jni/src/lib.rs#L1474) we can see this should not be happening, as it is `_class` there.

**Comment by birbe** [comment]
@schitcrafter didnt you fix this with that one PR

**Comment by schitcrafter** [comment]
No? There's no changes to the files in the .github directory since this was created so I don't think so

**Comment by schitcrafter** [comment]
Fixed by #73
