### ISSUE TITLE
Replace jni with project panama?

### ISSUE THREAD

**Issue by Kamillaova** [wgpu-mc/wgpu-mc#47]

**Comment by birbe** [comment]
Not sure how feasible this is. I'm not sure about:
- the development state of Project Panama
- if its suited to be used in a Rust calling Java context, and not just vice versa

Also, we'll need to do some benchmarking to figure out how much overhead the JNI actually incurs.

**Comment by MineGame159** [comment]
Last time I tried foreign linker the overhead was more or less the same as JNI but that was quite a while ago so it could be different now. Also foreign linker API is in preview which means it needs VM flags to enable it and it will be improved in the future.

As to calling java functions from native code that is fully possible as the API has both downcall and upcall handles. So if you can call a C function pointer in rust it should be fine.

**Comment by birbe** [comment]
Tests would be nice. If you wouldn't mind benchmarking some of the JNI code we also have, that would be handy. I can also get around to that myself today

**Comment by MineGame159** [comment]
Yeah, I don't mind making a simple benchmark with rust in a few hours

**Comment by Kamillaova** [comment]
btw also check this 

https://github.com/apangin/nalim

**Comment by birbe** [comment]
> btw also check this 
> 
> 
> 
> https://github.com/apangin/nalim

I saw this before but forgot about it. Seems worthwhile to research more. I still need to benchmark how long the jni crate actually spends doing say, array copies

**Comment by Kamillaova** [comment]
> I saw this before but forgot about it. Seems worthwhile to research more. I still need to benchmark how long the jni crate actually spends doing say, array copies

https://github.com/apangin/nalim#array-processing ...?

**Comment by birbe** [comment]
no, i meant how long our use case deals with it. on my system (i switched over to using critical loads and I think it shaved a few milliseconds off) its about 10ms in total to call the native method (measured from Java)

**Comment by birbe** [comment]
Closing this for now as Project Panama isn't even really in a usable state afaik

**Comment by Zensonaton** [comment]
> Closing this for now as Project Panama isn't even really in a usable state afaik

Have you forgot about actually closing this issue, @birbe? 👀
