### ISSUE TITLE
Fix text rendering

### ISSUE THREAD

**Issue by schitcrafter** [wgpu-mc/wgpu-mc#48]
Tested on Pop_OS! 22.04 LTS, Linux 6.0.6

![image](https://user-images.githubusercontent.com/58911293/201524123-78f2909f-e572-4c57-8e81-0cb06acc555d.png)

**Comment by birbe** [comment]
its like that on all platforms, im not exactly sure which part is causing this. If I had to guess, it would be our implementation of glTexSubImage2D

**Comment by schitcrafter** [comment]
MC (or rather, TextureUtil.prepareImage) uses GlStateManager._texImage2D, not texSubImage2D. Doesn't change anything from the fact that this is very weird

**Comment by birbe** [comment]
texImage2D is a different thing

**Comment by Zanctarian** [comment]
Fixed #65
