### ISSUE TITLE
Chunks are in odd positions in Electrum

### ISSUE THREAD

**Issue by birbe** [wgpu-mc/wgpu-mc#57]
While running in Minecraft, it appears that the chunk data within a given chunk is valid (meaning there's no garbage data) but the chunks look like they're being rendered in odd positions. Seeing as there aren't any weird discontinuities in the rendered meshes, I assume that the issue is deeper than where the vertex shader thinks a chunk is, as in there's something weird with MinecraftBlockStateProvider or how it gets it's data

**Comment by Zanctarian** [comment]
Fixed #61
