### ISSUE TITLE
Mouse not fixed in position on Macos

### ISSUE THREAD

**Issue by Jomyy** [wgpu-mc/wgpu-mc#59]
On Macos the mouse can go outside the window and won't control the game anymore

Ik it's like super minor but still something that eventually will have to get fixed

**Comment by birbe** [comment]
this shouldn't be closed as "not planned", vanilla MC obviously has some way to deal with this that hides the cursor. Maybe @The-Minecraft-Scientist could work on this. I have an M1 Mac but I don't really use it a lot for developing wgpu-mc anymore

**Comment by The-Minecraft-Scientist** [comment]
I’ll take a look at it. The cleanest way to fix this is probably just to pr it upstream in winit.

**Comment by birbe** [comment]
I don't think there's anything to upstream in winit. What we need to do is just implement returning the mouse cursor to the middle of the window

**Comment by The-Minecraft-Scientist** [comment]
#97 fixes this
