### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by terrarier2111** [wgpu-mc/wgpu-mc#6]
Hi, i am one of the members(and maintainers) of the Leafish project. Our goal is to provide an open-source rust implementation of a client which can join on java servers with versions 1.7.10-latest(with all these versions being supported by a single executable). The client can already be used to join on servers and interact with the world, although there are some bugs (notably missing textures on higher versions) and missing features(notable there is no support for microsoft accounts/auth)  the client runs smoothly with 400+ fps. We are currently in the process of switching from OpenGL to WGPU. But as i am new to WGPU and new-ish to rendering in general it is really challenging to do so and requires a good chunk of work. That's there this project comes into play, i stumbled upon it while searching for wgpu things. And i have to say, it looks really promising, although there are some features missing, it's exactly what we needed. My question here really is: is this project in active development (in terms of functionality)? and would you be interested in helping us to use this as our new renderer once this project is ready to be used?
Here is a link to our project: https://github.com/Lea-fish/Leafish
Btw: We would ofc give you (in-game and out-game) credits if this collaboration works out which could boost this amazing project.

**Comment by Birbe** [comment]
> My question here really is: is this project in active development (in terms of functionality)? 

Yep! I'm spending a lot of my time working on it. It already has certain basic (world rendering) features implemented independently of the game and working in the wgpu-mc-demo crate. The code was a little bit messy as this is my first wgpu project but as I've been getting the hang of it I've been cleaning up the code, this includes upgrading it from wgpu 0.6 to 11.0, which took a chunk of time but is now essentially complete. I'm spending a lot of time working on interfacing with the actual game itself, and within a couple days (110% within the month) GUIs and world rendering should be decently implemented.

> Would you be interested in helping us to use this as our new renderer once this project is ready to be used?

Sure! The renderer is quite independent of the game (in terms of whether or not it needs Java Edition to be able to work), so you should definitely be able to use it.

**Comment by Birbe** [comment]
I've joined the Discord server if you'd like to further discussion there.

**Comment by Birbe** [comment]
Closing this for now as any further work should be done in the Leafish GitHub. The necessary features are at a point that you Leafish should be able to get started porting the OpenGL code to wgpu-mc
