### ISSUE TITLE
Chunks getting more distorted the bigger your coordinates are

### ISSUE THREAD

**Issue by RealLily** [wgpu-mc/wgpu-mc#63]
# Chunks getting more distorted the bigger your coordinates are

I've noticed that the chunks in my game are getting more distorted the bigger the player's coordinates are. For example, at (0, 100, 0) the chunks look fine, but at (1000000, 100, 1000000) they appear stretched and distorted. I believe this is an issue with the way the chunks are being generated and rendered.

## Steps to reproduce
1. Start a new game
2. Move the player to coordinates (1000000, 100, 1000000) or higher
3. Observe the distorted chunks

## Expected behavior
Chunks should be generated and rendered correctly, regardless of the player's coordinates.

## Screenshots
https://cdn.discordapp.com/attachments/903679407128993825/1064267889487655042/image.png

## Additional context
- Game version: Commit a9dc10aacd736c5661f0f86a63c725d2a7320eac
- Platform: Windows 11
- Additional Information: This issue was made with chat-gpt.

**Comment by birbe** [comment]
Knew this would happen but didn't bother to change it yet. Its just a floating point accuracy issue. Ill fix it soon

**Comment by birbe** [comment]
The fix is mostly implemented (and has been for a long time) but there are some lingering issues with modulo math or something, because the chunks jump around when I adjust their offset in the vertex shader

**Comment by birbe** [comment]
fixed
