### ISSUE TITLE
Create a lighting engine

### ISSUE THREAD

**Issue by Birbe** [wgpu-mc/wgpu-mc#8]
Provide an array of light sources, along with information such as intensity and color.
Also provide a lightmap

**Comment by BGR360** [comment]
For the record, the Minecraft client doesn't do any lighting calculations to my knowledge. The server sends over what is essentially "baked" lighting for each chunk, a "sky light level" and "block light level" for each block. Those two values are mapped to UV coordinates into a fixed lightmap texture.

See here for more info: https://greyminecraftcoder.blogspot.com/2020/04/lighting-1144.html

**Comment by Birbe** [comment]
Hmm thats true

**Comment by BGR360** [comment]
I'm not sure how item lighting works though. That might require some work in this vein.

**Comment by Birbe** [comment]
Considering the project is also a standalone engine, a lighting engine is necessary

**Comment by lucsoft** [comment]
is non-Minecraft engine stuff really a scope for 1.0?

**Comment by Birbe** [comment]
maybe not

**Comment by Birbe** [comment]
Probably out of the scope of this project, especially with #29. Closing this for now
