### ISSUE TITLE
Fix main menu background

### ISSUE THREAD

**Issue by suprohub** [wgpu-mc/wgpu-mc#95]
Oh my god this looks.. Uhm.. 
![image-55.png](https://github.com/wgpu-mc/wgpu-mc/assets/125716028/3355b7e5-7213-4888-a60d-7b52189c55bf)

I think it's not that hard to fix

**Comment by Zanctarian** [comment]
This is an on/off project for me. There's an issue deep in the rendering engine involving matrix transformation that I can't figure out yet. I can only get the front, back, and top faces to display on the cubemap, but not the other 3. Looking into renderdoc, it seems those 3 somehow get inverted.. positive to negative and vice versa. Not sure yet what exactly is causing it, but if I can get all 6 faces to show, it'll be smooth sailing from there.

**Comment by birbe** [comment]
Fixed, see #100
